export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";

export const FETCH_MOVIES = "FETCH_MOVIES"
export const FETCH_VALUE = "FETCH_VALUE"

export const ADD_FAVOURITE ="ADD_FAVOURITE"
export const FAVOURITE_MOVIES = "FAVOURITE_MOVIES"
export const DELETE_FROM_FAVOURITE_MOVIES = "DELETE_FROM_FAVOURITE_MOVIES"

export const SELECTED_MOVIE = "SELECTED_MOVIE"

export const RECENTLY_SEARCHED_MOVIES = "RECENTLY_SEARCHED_MOVIES"


export const GET_LOCATIONS = "GET_LOCATIONS";


export const LOADING_TRUE="LOADING_TRUE";
export const LOADING_FALSE="LOADING_FALSE";


